name: jxcryptledger
description: "JxCryptLedger Transaction Manager."
publish_to: 'none'
version: 1.0.2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.1.0
  cryptography: ^2.9.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5
  get_it: ^9.2.0
  flutter_dotenv: ^6.0.0
  pinyin: ^3.3.0
  http: ^1.6.0
  decimal: ^3.2.4
  intl: ^0.20.2
  flutter_typeahead: ^4.8.0
  uuid: ^4.0.0
  data_table_2: ^2.7.2
  animated_tree_view: ^2.3.0

dev_dependencies:
  dotenv: ^4.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.13

flutter:
  assets:
    - .env 
    - assets/icon.png
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
    icon_size: 256
  linux:
    generate: true
    icon_name: "jxledger"

msix_config:
  display_name: JxLedger
  publisher_display_name: Jason Xie
  identity_name: com.duckzland.jxcryptledger
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  install_certificate: true